# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationaldex', models.IntegerField(default=0)),
                ('localdex', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('caught', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('nationaldex',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.FloatField(default=0)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('generation',),
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livingdex_app.Region'),
        ),
    ]
